---
title: "School participation across the year"
author: "Merly Klaas"
date: "2023-09-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load(rio, here, dplyr,tidyverse,lubridate, ggplot2,viridis)
```


```{r}
school <- import(here("data", "sort.csv"))

```

## Number of school participated each year

```{r}
school %>% 
  select(starts_with("year")) %>% 
  colSums(na.rm=TRUE)
  
```

## school's participation across the year

We only have 25 schools participated across 4 year out of 514 total schools.

```{r}
school %>% 
  count(total_count) %>% 
  ggplot()+
  geom_col(aes(total_count, n), fill="blue") +
  geom_text(aes(total_count, n,label = n))
```

```{r}
school %>% 
  pivot_longer(cols = 2:6,
               names_to = "year",
               values_to = "count", 
               names_prefix = "year_") %>% 
   ggplot() +
  geom_tile(aes(year, school_name, fill=count))+
   scale_fill_viridis(discrete=FALSE, direction=-1)+
  theme(axis.text.y = element_blank(),
        axis.title.y = element_blank())
```

```{r}


```


