---
title: "Longitudinal Quick Facts"
author: "Janette Avelar"
date: '2024-09-20'
output: 
  html_document:
    toc: true
    toc_float: true
    theme: flatly
    highlight: tango
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warnings = FALSE, message = FALSE, fig.width = 8, fig.height = 6)
pacman::p_load(tidyverse, here, rio, DT, ggthemes, scales, statebins, ggbreak)
#read in data
load(here("data", "2024 data/complete_canopy_2024.RData"))
dat <- variables
rm(dictionary, full, tags, variables)
```

```{r}
#manual branding - file won't load
transcend_cols = c("#1A4C81","#59C3B4","#EF464B","#ADE0EE")
transcend_cols2 = c("#BC2582","#FFA630","#FFDE42","#99C24D","#218380","#D3B7D7")
transcend_grays = c("#4D4D4F","#9D9FA2","#D1D3D4")
transcend_na = transcend_grays[2]
theme_transcend = theme_gdocs(base_size = 14, base_family = "Open Sans") +
  theme(
    plot.title = element_text(family = "Bebas Neue", color = "black"),
    plot.background = element_blank(),
    axis.text = element_text(colour = "black"),
    axis.title = element_text(colour = "black"),
    panel.border = element_rect(colour = "#4D4D4F"),
    strip.text = element_text(size = rel(0.8)),
    plot.margin = margin(10, 24, 10, 10, "pt")
  )
theme_set(theme_transcend)
```

```{r}
#barplot function
barplot <- function(x, data, metric, palette = transcend_cols, title = "Some title", subtitle = "Sample limited to schools that participated 2 or more times in a Canopy survey (N = 263)."){
  # Ensure metric is a character string
  if (!is.character(metric) || length(metric) != 1) {
    stop("Metric must be a single character string indicating 'n' or 'pct'.")
  }
  
  data <- data %>% 
    mutate(rate = 1) %>% 
    group_by({{x}}) %>% 
    summarize(n = sum(rate)) %>% 
    ungroup() %>% 
    mutate(total = sum(n),
           pct = n/total) %>% 
    filter(!is.na({{x}}))
  
  y_var <- ifelse(metric == "n", "n", "pct")
  y_lab <- ifelse(metric == "n", "Number of schools", "Percentage of schools")

  # Setup plot
  plot <- ggplot(data, aes(x = {{x}}, y = .data[[y_var]], fill = {{x}})) +
    geom_col() +
    scale_fill_manual(values = palette) +
    theme(legend.position = "none", panel.grid.major.x = element_blank()) +
    labs(title = str_wrap(title, 55), subtitle = str_wrap(subtitle, 79), x = "", y = y_lab)
  
  # Configure y-axis and labels based on metric
  if (metric == "n") {
    max_y <- max(data[[y_var]], na.rm = TRUE)
    limit_upper <- max_y * 1.1
    plot <- plot + scale_y_continuous(expand = c(0, 0), limits = c(0, limit_upper))
    plot <- plot + geom_text(aes(label = n), nudge_y = 0.5, vjust = 0, color = transcend_na, fontface = "bold", size = 5.5, family = "sans")
  } else if (metric == "pct") {
    plot <- plot + scale_y_continuous(expand = c(0, 0), limits = c(0, 1), labels = scales::percent_format())
    plot <- plot + geom_text(aes(label = scales::label_percent(accuracy = 1)(pct)), nudge_y = 0.01, vjust = 0, color = transcend_na, fontface = "bold", size = 5.5, family = "sans")
  }
  
  return(plot)
}
```

Note: There are 263 repeating schools represented (2+ years of data)

```{r}
#limit data to repeating schools
repeaters <- import(here("data/longitudinal", "tags-long.csv")) %>% 
  group_by(school_id) %>% 
  summarize(n_years = n_distinct(year)) %>% 
  filter(n_years > 1) %>% 
  pull(school_id)
dat <- dat %>% 
  filter(school_id %in% repeaters)
```

## Locale

```{r}
png(filename = "output/janette-images/figure_25.png",
    width = 9,
    height = 7,
    units = "in",
    res = 300)
barplot(school_locale, dat, 'pct', transcend_cols, "Canopy schools by geographic region")
dev.off()
```

## Level

```{r}
png(filename = "output/janette-images/figure_26.png",
    width = 9,
    height = 7,
    units = "in",
    res = 300)
dat %>% 
  pivot_longer(cols = c("grades_pk", "grades_elementary", "grades_middle", "grades_high"),
               names_to = "school_level",
               values_to = "school_level_value",
               names_prefix = "grades_") %>% 
  filter(school_level_value == 1) %>% 
  group_by(school_level) %>% 
  summarize(n = sum(school_level_value),
            pct = n/189) %>% 
  mutate(school_level = factor(school_level, levels = c("pk", "elementary", "middle", "high"), labels = c("PreK", "Elementary", "Middle", "High"))) %>% 
  ggplot(., aes(school_level, y = pct, fill = school_level)) +
    geom_col() +
    scale_fill_manual(values = transcend_cols) +
    theme(legend.position = "none", panel.grid.major.x = element_blank()) +
    labs(title = "Canopy schools by level", 
         subtitle = str_wrap("Sample limited to schools that participated 2 or more times in a Canopy survey (N = 263).", 79),
           x = "", 
         y = "Percentage of schools") +
    scale_y_continuous(expand = c(0, 0), 
                       limits = c(0, 1), 
                       labels = scales::percent_format()) + 
    geom_text(aes(label = scales::label_percent(accuracy = 1)(pct)), 
              nudge_y = 0.01, 
              vjust = 0, 
              color = transcend_na, 
              fontface = "bold", 
              size = 5.5, 
              family = "sans")
dev.off()
```

## Type

```{r}
#save plot
png(filename = "output/janette-images/figure_27.png",
    width = 9,
    height = 7,
    units = "in",
    res = 300)
#plot
barplot(school_type, dat, 'pct', transcend_cols, "Canopy schools by type", subtitle = ) +
  scale_x_discrete(labels = wrap_format(20))
dev.off()
```

