---
title: "Finalized Report Figures"
author: "Janette Avelar"
date: '2024-10-24'
output: 
  html_document:
    toc: true
    toc_float: true
    theme: flatly
    highlight: tango
    code_folding: hide
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, fig.width = 7, fig.height = 6)
pacman::p_load(tidyverse, here, rio, ggthemes, scales, DT, stringi)
#read in data
load(here("data", "2024 data/complete_canopy_2024.RData"))
dat <- variables
rm(dictionary, full, variables)
long_dat <- import(here("data", "longitudinal/longitudinal_data.csv"))
long_tags <- import(here("data", "longitudinal/tags-long.csv"))
labels <- import(here("data", "longitudinal/tag-labels.csv")) %>% rename(var = variable)
```

```{r}
# Pull in Branding
# transcend_cols = c("#1A4C81","#59C3B4","#EF464B","#ADE0EE")
# transcend_cols2 = c("#BC2582","#FFA630","#FFDE42","#99C24D","#218380","#D3B7D7")
# transcend_grays = c("#4D4D4F","#9D9FA2","#D1D3D4")
# transcend_na = transcend_grays[2]
crpe_blues = c("#0178BA", "#62A3D0", "#A1C9E6")
crpe_oranges = c("#E38C34", "#F5C37D", "#F5C37D")
crpe_grays = c("#D9D9D9", "#E6E6E6", "#F2F2F2")
crpe_purples = c("#9467BD", "#B08CD3", "#C8B3E2")
theme_transcend = theme_gdocs(base_size = 14, base_family = "Open Sans") +
  theme(
    plot.title = element_text(family = "Helvetica Bold", color = "black"),
    plot.background = element_blank(),
    axis.text = element_text(colour = "black"),
    axis.title = element_text(colour = "black"),
    panel.border = element_rect(colour = "#4D4D4F"),
    strip.text = element_text(size = rel(0.8)),
    plot.margin = margin(10, 24, 10, 10, "pt")
  )
theme_set(theme_transcend)
```

```{r}
# File to save plots
# Updated from branding file - ggsave is causing unexpected crashing
save_plots <- function(
    plot, file, dir = here("output/report-figures"),
    fig_width = 9, fig_height = 7
) {
  # Directories for PNG and SVG
  png_dir <- file.path(dir, "png")
  svg_dir <- file.path(dir, "svg")
  
  # Ensure directories exist
  dir.create(png_dir, recursive = TRUE, showWarnings = FALSE)
  dir.create(svg_dir, recursive = TRUE, showWarnings = FALSE)
  
  # Define file paths
  png_file <- file.path(png_dir, paste0(file, ".png"))
  svg_file <- file.path(svg_dir, paste0(file, ".svg"))
  
  # Save as PNG
  tryCatch({
    png(filename = png_file, width = fig_width * 96, height = fig_height * 96, res = 96) # 96 dpi
    print(plot)  # Print plot to file
    dev.off()    # Close the file
    message(sprintf("Successfully saved PNG file to %s", png_file))
  }, error = function(e) {
    message("Failed to save PNG file: ", e$message)
  })
  
  # Save as SVG
  tryCatch({
    svg(filename = svg_file, width = fig_width, height = fig_height)
    print(plot)
    dev.off()
    message(sprintf("Successfully saved SVG file to %s", svg_file))
  }, error = function(e) {
    message("Failed to save SVG file: ", e$message)
  })
}

```


# Figure 1

```{r}
# Plot function
special_pops <- function(data, var, title, type = "plot"){
  
  # Make var workable
  var <- ensym(var)  
  
  # Create dataset for plot
  plot_dat <- data %>% 
    select(school_id, year, !!var) %>%  
    pivot_wider(names_from = year,
                values_from = !!var) %>%
    mutate(n_years = rowSums(!is.na(select(., -school_id)))) %>%
    filter(n_years > 1) %>% #OG 3
    pivot_longer(cols = c(`2019`:`2024`),
                 names_to = "year",
                 values_to = "value") %>%
    mutate(year = as.numeric(year),
           n_school = n_distinct(school_id)) %>% 
    filter(!is.na(value))  %>% 
    filter(value != 0)
  
  # Pull N for subtitle
  n_school <- plot_dat %>% 
    pull(n_school)
  
  # Check type of return requested
  if (type == "data") {
    return(plot_dat)
  }
  
  # Build plot if necessary
  plot <- ggplot(plot_dat, aes(x = year, y = value, group = school_id)) +  
      #geom_line(color = transcend_cols[1], alpha = 0.4) +
      geom_point(color = crpe_blues[1], alpha = 0.7, size = 1) +
      geom_smooth(se = FALSE, method = "loess", color = crpe_oranges[1], aes(group = 1)) +
      scale_x_continuous(limits = c(2019, 2024),
                         expand = c(0.01, 0),
                         breaks = unique(long_dat$year)) +
      scale_y_continuous(limits = c(0, 1),
                         expand = c(0, 0),
                         labels = scales::percent_format(accuracy = 1)) +
      theme(panel.grid.major.x = element_blank()) +
      labs(x = "",
           y = "",
           title = str_wrap(title, 50),
           subtitle = str_wrap(paste0("Sample includes all schools that completed two or more Canopy surveys between 2019-2024 (N = ", n_school, ")."), 80))
  
  return(plot)
}
```


## 1a - EL

```{r}
fig_1a <- special_pops(long_dat, pct_ell, "Percentage of Students Designated as English Learners")
save_plots(fig_1a, "figure_1a")
ggsave(filename = "output/report-figures/eps/figure_1a.eps",
       plot = fig_1a,
       device = "eps",
       width = 9,
       height = 7)
```

## 1b - SPED

```{r}
fig_1b <- special_pops(long_dat, pct_swd, "Percentage of Students with Disabilities")
save_plots(fig_1b, "figure_1b")
ggsave(filename = "output/report-figures/eps/figure_1b.eps",
       plot = fig_1b,
       device = "eps",
       width = 9,
       height = 7)
```

## 1c - BIPOC

```{r}
fig_1c <- special_pops(long_dat, pct_bipoc, "Percentage of Students of Color")
save_plots(fig_1c, "figure_1c")
ggsave(filename = "output/report-figures/eps/figure_1c.eps",
       plot = fig_1c,
       device = "eps",
       width = 9,
       height = 7)
```

## 1d - SES

```{r}
fig_1d <- special_pops(long_dat, pct_frpl, "Percentage of Socioeconomically Disadvantaged Students")
save_plots(fig_1d, "figure_1d")
ggsave(filename = "output/report-figures/eps/figure_1d.eps",
       plot = fig_1d,
       device = "eps",
       width = 9,
       height = 7)
```

## 1e - combined

```{r}
#Create dataset
variables <- c("pct_ell", "pct_swd", "pct_bipoc", "pct_frpl") 

# Function to loop through variables and extract data
extract <- map_dfr(variables, function(var) {
  data <- special_pops(long_dat, !!sym(var), title = var, type = "data")
  
  # Add a column to identify the variable
  data <- data %>% mutate(variable = var)
  
  return(data)
})

# Add titles for facet wrap
extract <- extract %>% 
  mutate(variable = case_when(
    variable == "pct_ell" ~ "Percentage of students designated as English learners",
    variable == "pct_swd" ~ "Percentage of students with disabilities",
    variable == "pct_bipoc" ~ "Percentage of students of color",
    variable == "pct_frpl" ~ "Percentage of economically disadvantaged students"))

# Pull new N
n_school <- extract %>% 
  summarize(n = n_distinct(school_id)) %>% 
  pull(n)
```

```{r}
fig_1e <- ggplot(extract, aes(year, value, group = school_id)) +  
  geom_point(color = crpe_blues[1], alpha = 0.5, size = 1) +
  geom_smooth(se = FALSE, method = "loess", color = crpe_oranges[1], aes(group = 1)) +
  scale_x_continuous(limits = c(2019, 2024),
                     expand = c(0.01, 0),
                     breaks = unique(long_dat$year)) +
  scale_y_continuous(limits = c(0, 1),
                     expand = c(0, 0),
                     labels = scales::percent_format(accuracy = 1)) +
  theme(panel.grid.major.x = element_blank(),
        panel.spacing = unit(1, "lines"),
        axis.text=element_text(size = 8)) +
  facet_wrap(~variable, 
             labeller = label_wrap_gen(width = 50), 
             scales = "free_x") +
      labs(x = "",
           y = "",
           title = str_wrap("Special Population Classifications Over Time", 90),
           subtitle = str_wrap(paste0("Blue dots represent individual schools, while orange lines represent the average trend. Sample limited to schools that participated 2 or more times in a Canopy survey and reported demographic data (N = ", n_school, ")."), 80))
save_plots(fig_1e, "figure_1e")
ggsave(filename = "output/report-figures/eps/figure_1e.eps",
       plot = fig_1e,
       device = "eps",
       width = 9,
       height = 7)
```

```{r}
# Clean up
rm(fig_1a, fig_1b, fig_1c, fig_1d, fig_1e, n_school, variables, special_pops, extract)
```

# Figure 2

```{r}
# Capitalize tag names in labels
labels$label <- paste0(toupper(substr(labels$label, 1, 1)), substr(labels$label, 2, nchar(labels$label)))
# Build plot
fig_2 <- tags %>% 
  select(school_id, starts_with("pilot")) %>% 
  pivot_longer(cols = starts_with("pilot"),
               names_to = "var",
               values_to = "usage") %>% 
  group_by(var) %>% 
  summarize(n = sum(usage),
            pct = round(n/189, 2)) %>% 
  mutate(var = str_replace_all(var, "pilot", "practices"),
         n_lab = paste0(n, " schools")) %>% 
  left_join(labels, by = "var") %>% 
  arrange(-n) %>% 
  slice_head(n = 5) %>% 
  ggplot(., aes(n, reorder(label, n))) +
  geom_col(fill = crpe_blues[1]) +
  scale_x_continuous(expand = c(0, 0),
                     limits = c(0, 30)) + 
  scale_y_discrete(labels = wrap_format(25)) +
  geom_text(aes(label = n_lab), #aes(label = scales::label_percent(accuracy = 1)(pct) 
            hjust = 1.1,
            vjust = 0, 
            color = "white", 
            size = 5.5, 
            family = "sans") +
  theme(panel.grid.major.y = element_blank(),
        axis.text.y = element_text(size = 12)) +
  labs(title = str_wrap("Top 5 Practices Canopy Schools Plan to Pilot in the Next 5 Years", 40),
       subtitle = str_wrap("Sample limited to schools that participated in 2024 Canopy survey (N = 189).", 65),
       x = "Number of Canopy schools",
       y = "")
save_plots(fig_2, "figure_2")
ggsave(filename = "output/report-figures/eps/figure_2.eps",
       plot = fig_2,
       device = "eps",
       width = 9,
       height = 7)
```

```{r}
# Clean up
rm(fig_2)
```

# Figure 3

```{r}
barrier_labs <- dat %>% 
  select(starts_with("barrier"), -barrier_other_text) %>% 
  pivot_longer(cols = starts_with("barrier"),
               names_to = "barrier",
               values_to = "response") %>% 
  select(barrier) %>% 
  unique() %>% 
  mutate(label = case_when(
    barrier == "barrier_local_funds" ~ "Availability of local funds",
    barrier == "barrier_private_funds" ~ "Availability of private funding from foundations or donors",
    barrier == "barrier_donations" ~ "Changes to in-kind donations",
    barrier == "barrier_inflation" ~ "Inflation/increasing prices",
    barrier == "barrier_enrollment" ~ "Changes in school enrollment",
    barrier == "barrier_shortage" ~ "Staffing shortages",
    barrier == "barrier_federal_funds" ~ "Expiration of federal relief funds",
    barrier == "barrier_other" ~ "Some other reason"
  ))
```

```{r}
fig_3 <- dat %>% 
  select(school_id, future_resources, starts_with("barrier"), -barrier_other_text) %>% 
  filter(future_resources == "Yes, extremely" | future_resources == "Yes, somewhat") %>% 
  pivot_longer(cols = contains("barrier"),
               names_to = "barrier",
               values_to = "response") %>% 
  group_by(barrier) %>% 
  summarize(n = sum(response),
            pct = n/115) %>% 
  left_join(barrier_labs, by = "barrier") %>% 
  mutate(pct = ifelse(label == "Some other reason", pct - .001, pct)) %>% 
  #plot
  ggplot(aes(pct, reorder(label, pct))) +
  geom_col(fill = crpe_blues[1]) +
  labs(title = str_wrap("Barriers to Financial Sustainability Canopy School Leaders Cited in 2024", 40),
       subtitle = str_wrap("Sample limited to schools that participated in 2024 Canopy survey (N = 189).", 67),
       x = "Percentage of Canopy schools",
       y = "") +
  theme(legend.position = "none",
        panel.grid.major.y = element_blank(),
        axis.text.y = element_text(size = 12)) +
  scale_x_continuous(label = scales::label_percent(), 
                     expand = c(0, 0), 
                     limits = c(0, 1)) +
  scale_y_discrete(labels = wrap_format(35)) +
  geom_text(aes(label = scales::label_percent(accuracy = 1)(pct)), 
            hjust = 1.1,
            vjust = 0, 
            color = "white", 
            size = 5.5, 
            family = "sans")
save_plots(fig_3, "figure_3")
ggsave(filename = "output/report-figures/eps/figure_3.eps",
       plot = fig_3,
       device = "eps",
       width = 9,
       height = 7)
```

```{r}
# Clean up
rm(barrier_labs, fig_3)
```

# Figure 4

```{r}
# Policy labels
policy_labs <- dat %>% 
  select(starts_with("policy")) %>% 
  pivot_longer(cols = starts_with("policy"),
               names_to = "policy",
               values_to = "response") %>% 
  select(policy) %>% 
  unique() %>% 
  mutate(short_label = case_when(
    policy == "policy_public_revenue" ~ "Public revenue",
    policy == "policy_philanthropy" ~ "Philanthropic funding",
    policy == "policy_schedule" ~ "Calendar/scheduling requirements",
    policy == "policy_graduation" ~ "Course progression, seat time, and graduation",
    policy == "policy_admissions" ~ "Admission requirements",
    policy == "policy_accountability" ~ "Accountability systems",
    policy == "policy_report_funders" ~ "Expectations from philanthropic funders",
    policy == "policy_service" ~ "Public service providers",
    policy == "policy_credentials" ~ "Credentialing/evaluation",
    policy == "policy_union" ~ "Labor contracts and/or union relationships",
    policy == "policy_enrollment" ~ "Enrollment, lottery, or school assignment"
  ))
```

```{r}
helps <- dat %>% 
  select(school_id, starts_with("policy")) %>% 
  pivot_longer(cols = starts_with("policy"),
               names_to = "policy",
               values_to = "response") %>% 
  mutate(rate = 1) %>% 
  group_by(policy, response) %>% 
  summarize(n = sum(rate)) %>% 
  ungroup() %>% 
  left_join(policy_labs, by = "policy") %>% 
  filter(response == "Really helps" | response == "Somewhat helps") %>% 
  mutate(response = factor(response, levels = c("Somewhat helps", "Really helps")))
```

```{r}
hinders <- dat %>% 
  select(school_id, starts_with("policy")) %>% 
  pivot_longer(cols = starts_with("policy"),
               names_to = "policy",
               values_to = "response") %>% 
  mutate(rate = 1) %>% 
  group_by(policy, response) %>% 
  summarize(n = sum(rate)) %>% 
  ungroup() %>% 
  left_join(policy_labs, by = "policy") %>% 
  filter(response == "Really hinders" | response == "Somewhat hinders") %>% 
  mutate(response = factor(response, levels = c("Somewhat hinders", "Really hinders")))
```

```{r}
fig_4 <- bind_rows(helps, hinders) %>% 
  mutate(n = ifelse(response == "Really hinders" | response == "Somewhat hinders", n*-1, n*1),
         response = factor(response, levels = c("Really hinders", "Somewhat hinders", "Really helps", "Somewhat helps"))) %>% 
  ggplot(., aes(n, reorder(short_label, n), fill = response)) +
  geom_col() +
  scale_fill_manual(values = c(
      "Really hinders" = crpe_oranges[1], 
      "Somewhat hinders" = crpe_oranges[2], 
      "Somewhat helps" = crpe_blues[2], 
      "Really helps" = crpe_blues[1])) +
  theme(legend.position = "top", 
        legend.direction = "horizontal",
        panel.grid.major.y = element_blank(),
        axis.text.y = element_text(size = 12),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        legend.text = element_text(size = 10)) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_discrete(labels = wrap_format(35)) +
  geom_text(aes(label = abs(n), x = n), 
            position = position_stack(vjust = .5), 
            color = "white", 
            size = 5.5, 
            family = "sans") +
  labs(x = "Number of Canopy schools",
       y = "",
       title = str_wrap("How Existing Policies and Ecosystem Factors Affect Canopy Schools' Work", 40),
       subtitle = str_wrap("Sample limited to schoools that participated in 2024 Canopy survey (N = 189).", 62),
       fill = "")
save_plots(fig_4, "figure_4")
ggsave(filename = "output/report-figures/eps/figure_4.eps",
       plot = fig_4,
       device = "eps",
       width = 9,
       height = 7)
```

```{r}
# Clean up
rm(fig_4, helps, hinders, policy_labs)
```

# Figure 5

```{r}
fig_5 <- dat %>% 
  select(school_id, future_resources, leadership_diversity) %>% 
  filter(future_resources != "Prefer not to say") %>% 
  mutate(future_resources = factor(future_resources,
                                   levels = c("No, not at all", "No, not very", "Neutral", "Yes, somewhat", "Yes, extremely")),
         rate = 1,
         leadership_diversity = str_replace_all(leadership_diversity, "people", "leaders"),
         leadership_diversity = gsub(" - ", "\u2013", leadership_diversity)) %>% 
  group_by(future_resources, leadership_diversity) %>% 
  summarize(n = sum(rate)) %>% 
  ungroup() %>% 
  group_by(leadership_diversity) %>% 
  mutate(sum = sum(n),
         pct = n/sum) %>% 
  ungroup() %>% 
  ggplot(., aes(pct, leadership_diversity, fill = future_resources)) +
  geom_col() +
  scale_fill_manual(values = c(
      "Yes, extremely" = crpe_oranges[1], 
      "Yes, somewhat" = crpe_oranges[2], 
      "Neutral" = crpe_grays[1],
      "No, not very" = crpe_blues[2], 
      "No, not at all" = crpe_blues[1])) +
  scale_x_continuous(expand = c(0, 0), limits = c(0, 1), labels = scales::percent_format()) +
  geom_text(aes(label = scales::label_percent(accuracy = 1)(pct)), 
            position = position_stack(vjust = .5), 
            color = "white", 
            size = 5, 
            family = "sans") +
  theme(legend.position = "bottom", 
        legend.direction = "horizontal", 
        panel.grid.major.y = element_blank(), 
        axis.text.y = element_text(size = 12),
        legend.text = element_text(size = 10),
        legend.title = element_text(size = 10)) +
  labs(x = "", 
       y = "", 
       title = str_wrap("Concern About Future Sustainability by Level of Racial Diversity in School Leadership", 40), #different for smaller plot
       subtitle = str_wrap("Leaders' responses to \"Are you concerned about your ability to sustain resources for your learning environment over the next five years?\" Sample limited to schools that participated in 2024 Canopy survey (N = 189).", 67), 
       fill = "Level of concern") +
  guides(fill = guide_legend(reverse = T, 
                             title.position = "top",
                             title.hjust = 0.5))
save_plots(fig_5, "figure_5", fig_width = 9, fig_height = 6)
ggsave(filename = "output/report-figures/eps/figure_5.eps",
       plot = fig_5,
       device = "eps",
       width = 9,
       height = 5)
```

```{r}
# Clean up
rm(fig_5)
```

# Figure 6

```{r}
# Pull relevant practices
blended <- c("practices_blended_learning", "practices_a_la_carte", "practices_flipped_classroom", "practices_flex", "practices_enriched_virtual", "practices_station_rotation")
# ID 3+ year schools
id <- long_tags %>% 
  select(school_id, year) %>% 
  group_by(school_id) %>% 
  summarize(n = n_distinct(year)) %>% 
  filter(n > 2) %>% 
  pull(school_id)
# Pull Ns for each year
n_2019 <- long_tags %>% filter(year == 2019 & school_id %in% id) %>% summarize(n = n_distinct(school_id)) %>% pull()
n_2021 <- long_tags %>% filter(year == 2021 & school_id %in% id) %>% summarize(n = n_distinct(school_id)) %>% pull()
n_2022 <- long_tags %>% filter(year == 2022 & school_id %in% id) %>% summarize(n = n_distinct(school_id)) %>% pull()
n_2023 <- long_tags %>% filter(year == 2023 & school_id %in% id) %>% summarize(n = n_distinct(school_id)) %>% pull()
n_2024 <- long_tags %>% filter(year == 2024 & school_id %in% id) %>% summarize(n = n_distinct(school_id)) %>% pull()
# Create pct col
fig_6 <- long_tags %>% 
  filter(school_id %in% id) %>% 
  filter(var %in% blended) %>% 
  group_by(var, year) %>% 
  summarize(n = sum(usage)) %>% 
  ungroup() %>% 
  mutate(pct = case_when(
    year == 2019 ~ n/n_2019,
    year == 2021 ~ n/n_2021,
    year == 2022 ~ n/n_2022,
    year == 2023 ~ n/n_2023,
    year == 2024 ~ n/n_2024
  )) %>% 
  left_join(labels, by = "var") %>% 
  ggplot(., aes(year, pct, color = label)) +
  geom_line() +
  geom_point() +
  scale_color_manual(values = c(crpe_blues[1], crpe_blues[3], crpe_oranges[1], crpe_oranges[3], crpe_purples[1], crpe_purples[3])) +
  scale_x_continuous(limits = c(2019, 2024),
                     expand = c(0.01, 0),
                     breaks = unique(long_dat$year)) +
  scale_y_continuous(expand = c(0, 0),
                     limits = c(0, 1),
                     labels = scales::percent_format(accuracy = 1)) +
  theme(panel.grid.major.x = element_blank(),
        legend.position = "bottom",
        legend.text = element_text(size = 10),
        legend.title = element_text(size = 10)) +
  labs(x = "",
       y = "Percentage of Canopy schools",
       title = str_wrap("Changes in Select Practices Related to Blended Learning 2019\u20132024", 48),
       subtitle = str_wrap("Sample limited to schools that participated 3 or more times in a Canopy survey (N = 119).", 80),
       color = "Blended learning practice") +
  guides(color = guide_legend(title.position = "top",
                              title.hjust = 0.5,
                              nrow = 2))
save_plots(fig_6, "figure_6")
ggsave(filename = "output/report-figures/eps/figure_6.eps",
       plot = fig_6,
       device = "eps",
       width = 9,
       height = 7)
```

```{r}
# Clean up
rm(fig_6, blended, id, n_2019, n_2021, n_2022, n_2023, n_2024)
```

# Figure 7

```{r}
# ID 2+ year schools
id <- long_dat %>% 
  group_by(school_id) %>% 
  summarize(n = n_distinct(year)) %>% 
  ungroup() %>% 
  filter(n > 1) %>% 
  pull(school_id)
# Build plot
fig_7 <- long_dat %>% 
  filter(school_id %in% id) %>% 
  mutate(rate = 1) %>% 
  group_by(school_locale) %>% 
  summarize(n = sum(rate)) %>% 
  ungroup() %>% 
  mutate(total = sum(n),
         pct = n/total) %>% 
  filter(!is.na(school_locale)) %>% 
  ggplot(., aes(school_locale, pct, fill = school_locale)) +
    geom_col() +
    scale_fill_manual(values = c(crpe_oranges[1], crpe_blues)) +
    scale_y_continuous(expand = c(0, 0),
                       labels = scales::percent_format(accuracy = 1),
                       limits = c(0, 1)) +
    theme(legend.position = "none", panel.grid.major.x = element_blank()) +
    labs(title = "Canopy Schools by Geographic Region",
         subtitle = str_wrap("Sample limited to schools that participated 2 or more times in a Canopy survey (N = 263).", 80),
         x = "", 
         y = "Percentage of Canopy schools") +
  geom_text(aes(label = scales::label_percent(accuracy = 1)(pct)),
            nudge_y = 0.01,
            vjust = 0,
            color = "black",
            size = 5.5,
            family = "sans")
save_plots(fig_7, "figure_7")
ggsave(filename = "output/report-figures/eps/figure_7.eps",
       plot = fig_7,
       device = "eps",
       width = 9,
       height = 7)
```

# Figure 8

```{r}
fig_8 <- long_dat %>% 
  select(school_id, grades_pk, grades_elementary, grades_middle, grades_high) %>% 
  filter(school_id %in% id) %>% 
  #create ever levels
  group_by(school_id) %>% 
  mutate(ever_pk = ifelse(any(grades_pk == 1), 1, 0),
         ever_elem = ifelse(any(grades_pk == 1), 1, 0),
         ever_mid = ifelse(any(grades_middle == 1), 1, 0),
         ever_high = ifelse(any(grades_high == 1), 1, 0)) %>% 
  ungroup() %>% 
  select(-starts_with("grades")) %>% 
  unique() %>% 
  summarize(n_prek = sum(ever_pk, na.rm = TRUE),
            n_elementary = sum(ever_elem, na.rm = TRUE),
            n_middle = sum(ever_mid, na.rm = TRUE),
            n_high = sum(ever_high, na.rm = TRUE)) %>% 
  pivot_longer(cols = everything(),
               names_to = "school_level",
               values_to = "n",
               names_prefix = "n_") %>% 
  mutate(pct = n/sum(n),
         school_level = factor(school_level,
                               levels = c("prek", "elementary", "middle", "high"),
                               labels = c("PreK", "Elementary", "Middle", "High"))) %>% 
  ggplot(., aes(school_level, pct, fill = school_level)) +
    geom_col() +
    scale_fill_manual(values = c(crpe_oranges[1], crpe_blues)) +
    scale_y_continuous(expand = c(0, 0),
                       labels = scales::percent_format(accuracy = 1),
                       limits = c(0, 1)) +
    theme(legend.position = "none", panel.grid.major.x = element_blank()) +
    labs(title = "Canopy Schools by Level",
         subtitle = str_wrap("Sample limited to schools that participated 2 or more times in a Canopy survey (N = 263).", 80),
         x = "", 
         y = "Percentage of Canopy schools") +
  geom_text(aes(label = scales::label_percent(accuracy = 1)(pct)),
            nudge_y = 0.01,
            vjust = 0,
            color = "black",
            size = 5.5,
            family = "sans")
save_plots(fig_8, "figure_8")
ggsave(filename = "output/report-figures/eps/figure_18.eps",
       plot = fig_18,
       device = "eps",
       width = 9,
       height = 7)
```

# Figure 9

```{r}
fig_9 <- long_dat %>% 
  filter(school_id %in% id) %>% 
  mutate(rate = 1) %>% 
  group_by(school_type) %>% 
  summarize(n = sum(rate)) %>% 
  ungroup() %>% 
  mutate(total = sum(n),
         pct = n/total) %>% 
  filter(!is.na(school_type)) %>% 
  ggplot(., aes(school_type, pct, fill = school_type)) +
    geom_col() +
    scale_fill_manual(values = crpe_blues) +
    scale_y_continuous(expand = c(0, 0),
                       labels = scales::percent_format(accuracy = 1),
                       limits = c(0, 1)) +
    scale_x_discrete(labels = wrap_format(20)) +
    theme(legend.position = "none", panel.grid.major.x = element_blank()) +
    labs(title = "Canopy Schools by Type",
         subtitle = str_wrap("Sample limited to schools that participated 2 or more times in a Canopy survey (N = 263).", 80),
         x = "", 
         y = "Percentage of Canopy schools") +
  geom_text(aes(label = scales::label_percent(accuracy = 1)(pct)),
            nudge_y = 0.01,
            vjust = 0,
            color = "black",
            size = 5.5,
            family = "sans")
save_plots(fig_9, "figure_9")
ggsave(filename = "output/report-figures/eps/figure_9.eps",
       plot = fig_9,
       device = "eps",
       width = 9,
       height = 7)
```

```{r}
# Clean up
rm(fig_7, fig_8, fig_9, id)
```

# Figure 10

```{r}
fig_10 <- dat %>% 
  select(school_id, future_resources, school_type) %>% 
  filter(future_resources != "Prefer not to say") %>% 
  mutate(future_resources = factor(future_resources,
                                   levels = c("No, not at all", "No, not very", "Neutral", "Yes, somewhat", "Yes, extremely")),
         rate = 1) %>% 
  group_by(future_resources, school_type) %>% 
  summarize(n = sum(rate)) %>% 
  ungroup() %>% 
  group_by(school_type) %>% 
  mutate(sum = sum(n),
         pct = n/sum) %>% 
  ungroup() %>% 
  ggplot(., aes(pct, school_type, fill = future_resources)) +
  geom_col() +
  scale_fill_manual(values = c(
      "Yes, extremely" = crpe_oranges[1], 
      "Yes, somewhat" = crpe_oranges[2], 
      "Neutral" = crpe_grays[1],
      "No, not very" = crpe_blues[2], 
      "No, not at all" = crpe_blues[1])) +
  scale_x_continuous(expand = c(0, 0), 
                     limits = c(0, 1), 
                     labels = scales::percent_format()) +
  scale_y_discrete(labels = wrap_format(25)) +
  geom_text(aes(label = scales::label_percent(accuracy = 1)(pct)), 
            position = position_stack(vjust = .5), 
            color = "white", 
            size = 5, 
            family = "sans") +
  theme(legend.position = "bottom", 
        legend.direction = "horizontal", 
        panel.grid.major.y = element_blank(), 
        axis.text.y = element_text(size = 12),
        legend.text = element_text(size = 10),
        legend.title = element_text(size = 10)) +
  labs(x = "", 
       y = "", 
       title = str_wrap("Concern About Future Sustainability by Sector", 40), #different for smaller plot
       subtitle = str_wrap("Leaders' responses to \"Are you concerned about your ability to sustain resources for your learning environment over the next five years?\" Sample limited to schools that participated in 2024 Canopy survey (N = 189).", 67), 
       fill = "Level of concern") +
  guides(fill = guide_legend(reverse = T, 
                             title.position = "top",
                             title.hjust = 0.5))
save_plots(fig_10, "figure_10", fig_width = 9, fig_height = 5)
ggsave(filename = "output/report-figures/eps/figure_10.eps",
       plot = fig_10,
       device = "eps",
       width = 9,
       height = 5)
```

```{r}
# Clean up 
rm(fig_10)
```

# Figure 11

```{r}
# Question was optional - pull number of respondents who chose to answer
denom <- dat %>% 
  select(school_id, starts_with("catalyst"), -starts_with("catalyst_key"), -catalyst_other_text) %>% 
  pivot_longer(cols = starts_with("catalyst"),
               values_to = "n",
               names_to = "catalyst") %>% 
  group_by(school_id) %>% 
  mutate(selected_any = ifelse(any(n == 1), 1, 0)) %>% 
  ungroup() %>% 
  select(school_id, selected_any) %>% 
  unique() %>% 
  summarize(n = sum(selected_any)) %>% 
  pull(n)
# Build plot
fig_11 <- dat %>% 
  select(starts_with("catalyst"), -starts_with("catalyst_key"), -catalyst_other_text) %>% 
  pivot_longer(cols = everything(),
               names_to = "catalyst",
               values_to = "n",
               names_prefix = "catalyst_") %>% 
  group_by(catalyst) %>% 
  summarize(n = sum(n),
            pct = n/denom) %>% 
  mutate(catalyst = case_when(
    catalyst == "absence" ~ "Chronic absenteeism",
    catalyst == "covid" ~ "Learning disruptions due to COVID",
    catalyst == "cutting_edge" ~ "Desire to be on the cutting edge",
    catalyst == "demographics" ~ "Change in demographics",
    catalyst == "external" ~ "External catalyst events",
    catalyst == "inequities" ~ "Systemic inequities",
    catalyst == "internal" ~ "Negative factors inside the school",
    catalyst == "mental_health" ~ "Mental health concerns",
    catalyst == "other" ~ "Some other reason",
    catalyst == "stakeholders" ~ "Stakeholder demand or advocacy",
    catalyst == "student_agency" ~ "Lack of student agency",
    catalyst == "teacher_agency" ~ "Lack of teacher agency",
    TRUE ~ NA
  )) %>% 
  ggplot(., aes(pct, reorder(catalyst, pct))) +
  geom_col(fill = crpe_blues[1]) +
  labs(title = str_wrap("Factors Leading to Innovation in Canopy Schools", 35),
       subtitle = str_wrap("School leaders could select as many responses as applicable to their schools. Sample limited to schools that participated in 2024 Canopy survey (N = 189).", 60),
       x = "Percentage of Canopy schools",
       y = "") +
  theme(legend.position = "none",
        panel.grid.major.y = element_blank(),
        axis.text.y = element_text(size = 12)) +
  scale_x_continuous(label = scales::label_percent(), 
                     expand = c(0, 0), 
                     limits = c(0, 1)) +
  scale_y_discrete(labels = wrap_format(35)) +
  geom_text(aes(label = scales::label_percent(accuracy = 1)(pct)), 
            hjust = 1.1,
            vjust = 0, 
            color = "white", 
            size = 5.5, 
            family = "sans")
save_plots(fig_11, "figure_11")
ggsave(filename = "output/report-figures/eps/figure_11.eps",
       plot = fig_11,
       device = "eps",
       width = 9,
       height = 7)
```

```{r}
# Clean up
rm(fig_11, denom)
```

# Figure 12

```{r}
# Prep
# ID 3+ year schools
id <- long_tags %>% 
  select(school_id, year) %>% 
  group_by(school_id) %>% 
  summarize(n_year = n_distinct(year)) %>% 
  ungroup() %>% 
  filter(n_year > 2) %>% 
  pull(school_id)
# Pull Ns
# Pull Ns for each year
n_2019 <- long_tags %>% filter(year == 2019 & school_id %in% id) %>% summarize(n = n_distinct(school_id)) %>% pull()
n_2021 <- long_tags %>% filter(year == 2021 & school_id %in% id) %>% summarize(n = n_distinct(school_id)) %>% pull()
n_2022 <- long_tags %>% filter(year == 2022 & school_id %in% id) %>% summarize(n = n_distinct(school_id)) %>% pull()
n_2023 <- long_tags %>% filter(year == 2023 & school_id %in% id) %>% summarize(n = n_distinct(school_id)) %>% pull()
n_2024 <- long_tags %>% filter(year == 2024 & school_id %in% id) %>% summarize(n = n_distinct(school_id)) %>% pull()
```

```{r}
# Pull relevant tags
subset <- c("practices_sel_integrated", "practices_culturally_responsive", "practices_mental_health", "practices_trauma_informed", "practices_restorative")
# Build plot
fig_12 <- long_tags %>% 
  filter(var %in% subset) %>% 
  filter(school_id %in% id) %>% 
  group_by(var, year) %>% 
  summarize(n = sum(usage)) %>% 
  mutate(pct = case_when(
    year == 2019 ~ n/n_2019,
    year == 2021 ~ n/n_2021,
    year == 2022 ~ n/n_2022,
    year == 2023 ~ n/n_2023,
    year == 2024 ~ n/n_2024
  )) %>% 
  left_join(labels, by = "var") %>% 
  mutate(label = ifelse(label == "Trauma-informed practices", "Trauma-informed practices (first surveyed in 2021)", label)) %>% 
  ggplot(., aes(year, pct, color = label)) +
  geom_line() +
  geom_point() +
  scale_color_manual(values = c(crpe_blues[1], crpe_blues[3], crpe_oranges[1], crpe_purples[1], crpe_purples[3])) +
  scale_x_continuous(limits = c(2019, 2024),
                     expand = c(0.01, 0),
                     breaks = unique(long_dat$year)) +
  scale_y_continuous(expand = c(0, 0),
                     limits = c(0, 1),
                     labels = scales::percent_format(accuracy = 1)) +
  theme(panel.grid.major.x = element_blank(),
        legend.position = "bottom",
        legend.text = element_text(size = 10),
        legend.title = element_text(size = 10)) +
  labs(x = "",
       y = "Percentage of Canopy schools",
       title = str_wrap("Changes in Select Practices Related to Student Well-being and Equity 2019\u20132024", 48),
       subtitle = str_wrap("Sample limited to schools that participated 3 or more times in a Canopy survey (N = 119).", 80),
       color = "Select practices") +
  guides(color = guide_legend(title.position = "top",
                              title.hjust = 0.5,
                              nrow = 2))
save_plots(fig_12, "figure_12")
ggsave(filename = "output/report-figures/eps/figure_12.eps",
       plot = fig_12,
       device = "eps",
       width = 9,
       height = 7)
```

```{r}
# Clean up
rm(subset, fig_12)
```

# Figure 13

```{r}
# Pull relevant tags
subset <- c("practices_extended_learning", "practices_career_prep", "practices_assessments_career", "practices_community_partnerships")
# Build plot
fig_13 <- long_tags %>% 
  filter(var %in% subset) %>% 
  filter(school_id %in% id) %>% 
  group_by(var, year) %>% 
  summarize(n = sum(usage)) %>% 
  mutate(pct = case_when(
    year == 2019 ~ n/n_2019,
    year == 2021 ~ n/n_2021,
    year == 2022 ~ n/n_2022,
    year == 2023 ~ n/n_2023,
    year == 2024 ~ n/n_2024
  )) %>% 
  left_join(labels, by = "var") %>% 
  ggplot(., aes(year, pct, color = label)) +
  geom_line() +
  geom_point() +
  scale_color_manual(values = c(crpe_blues[1], crpe_blues[3], crpe_oranges[1], crpe_purples[1])) +
  scale_x_continuous(limits = c(2019, 2024),
                     expand = c(0.01, 0),
                     breaks = unique(long_dat$year)) +
  scale_y_continuous(expand = c(0, 0),
                     limits = c(0, 1),
                     labels = scales::percent_format(accuracy = 1)) +
  theme(panel.grid.major.x = element_blank(),
        legend.position = "bottom",
        legend.text = element_text(size = 10),
        legend.title = element_text(size = 10)) +
  labs(x = "",
       y = "Percentage of Canopy schools",
       title = str_wrap("Changes in Select Practices Related to Postsecondary Pathways 2019\u20132024", 40),
       subtitle = str_wrap("Sample limited to schools that participated 3 or more times in a Canopy survey (N = 119).", 80),
       color = "Select practices") +
  guides(color = guide_legend(title.position = "top",
                              title.hjust = 0.5,
                              nrow = 2))
save_plots(fig_13, "figure_13")
ggsave(filename = "output/report-figures/eps/figure_13.eps",
       plot = fig_13,
       device = "eps",
       width = 9,
       height = 7)
```

```{r}
# Clean up
rm(fig_13, id, n_2019, n_2021, n_2022, n_2023, n_2024, subset)
```

# Figure 14

```{r}
# Pulling numbers from Chelsea's spreadsheet `Early analysis for launch article - Canopy school survey 2024`
# AI tab
response <- c("No, we do not have an AI policy", "No, but we are in the process of developing one", "Yes, we have an AI policy")
values <- c(.54, .38, .07)
ai <- data.frame(response = response, 
                 pct = values)
fig_14 <- ggplot(ai, aes(reorder(response, pct), pct)) +
  geom_col(fill = crpe_blues[1]) +
  scale_y_continuous(label = scales::label_percent(), 
                     expand = c(0, 0), 
                     limits = c(0, 1)) +
  scale_x_discrete(labels = wrap_format(28)) +
  labs(title = str_wrap("Schools' Adoption of Policies for Student Use of Generative AI", 48),
       subtitle = str_wrap("Sample limited to schools that participated in 2024 Canopy survey (N = 189).", 80),
       x = "",
       y = "Percentage of Canopy schools") +
  theme(legend.position = "none",
        panel.grid.major.x = element_blank(),
        axis.text.x = element_text(size = 12)) +
  geom_text(aes(label = scales::label_percent(accuracy = 1)(pct)),
            nudge_y = 0.01,
            vjust = 0,
            color = "black",
            size = 5.5,
            family = "sans")
save_plots(fig_14, "figure_14")
ggsave(filename = "output/report-figures/eps/figure_14.eps",
       plot = fig_14,
       device = "eps",
       width = 9,
       height = 7)
```

```{r}
# Clean up
rm(response, values, ai, fig_14)
```

# Figure 15

```{r}
# Prep - Gregor's code from schools-practices-over-time.Rmd
changes_by_year = long_tags |>
  filter(n_distinct(year) > 1, .by = school_id) |>
  arrange(school_id, var, year) |>
  mutate(
    prev = lag(usage, default = NA), 
      ## this should be NA if the tag was not used previously
    diff = usage - lag(usage, default = NA),
    .by = c(var, school_id)
  ) |>
  slice(-1, .by = c(school_id, var)) |> ## drop first responses by school and tag
  summarize(
    n_adds = sum(diff == 1, na.rm = TRUE),
    n_drops = sum(diff == -1, na.rm = TRUE),
    n_changes = sum(diff != 0, na.rm = TRUE),
    n_same = sum(diff == 0, na.rm = TRUE),
    n_kept_1 = sum(diff == 0 & usage == 1, na.rm = TRUE),
    n_kept_0 = sum(diff == 0 & usage == 0, na.rm = TRUE),
    n_prev_1 = sum(prev == 1, na.rm = TRUE),
    n_prev_0 = sum(prev == 0, na.rm = TRUE),
    n_prev_all = sum(!is.na(prev), na.rm = TRUE),
    .by = c(school_id, year)
  ) |>
  mutate(
    prop_changed = n_changes / n_prev_all,
    prop_same = n_same / n_prev_all,
  )
# Prep for plot
unchanged_summary = changes_by_year |>
  summarize(
    mean_unchanged = mean(prop_same),
    sd_unchanged = sd(prop_same),
    q1_unchanged = quantile(prop_same, 0.25),
    q3_unchanged = quantile(prop_same, 0.75),
    n_year = n(),
    .by = year
  )
# Build plot
fig_15 <- ggplot(unchanged_summary, aes(x = mean_unchanged, y = year)) +
  geom_pointrange(
    aes(xmin = q1_unchanged, xmax = q3_unchanged),
    color = crpe_blues[1]
  ) +
  scale_x_continuous(
    labels = scales::label_percent(),
    limits = c(0.6, 1),
    expand = expansion(0, 0)
  ) +
  labs(
    title = str_wrap("Consistency of Canopy Schools' Practices Over Time", 45),
    subtitle = str_wrap("Percentage of practices unchanged from Canopy schools' previous response. Dots indicate the average, while bars highlight where the middle 50% of responses typically fall. Sample limited to schools that participated 2 or more times in a Canopy survey (N = 263).", 80),
    y = "",
    x = "Percentage of unchanged practices"
  ) +
  theme(
    panel.grid.major.y = element_blank()
  )
save_plots(fig_15, "figure_15")
ggsave(filename = "output/report-figures/eps/figure_15.eps",
       plot = fig_15,
       device = "eps",
       width = 9,
       height = 7)
```

```{r}
# Clean up
rm(changes_by_year, unchanged_summary, fig_15)
```


# Figure 16

```{r}
# Question was optional - pull number of respondents who chose to answer
denom <- dat %>% 
  select(school_id, starts_with("support"), -starts_with("support_key"), -support_other_text) %>% 
  pivot_longer(cols = starts_with("support"),
               values_to = "n",
               names_to = "support") %>% 
  group_by(school_id) %>% 
  mutate(selected_any = ifelse(any(n == 1), 1, 0),) %>% 
  ungroup() %>% 
  select(school_id, selected_any) %>% 
  unique() %>% 
  summarize(n = sum(selected_any)) %>% 
  pull(n)
# Build plot
fig_16 <- dat %>% 
  select(starts_with("support"), -c(support_other, support_key_other, support_other_text)) %>% 
  pivot_longer(cols = starts_with("support"),
               names_to = "support",
               values_to = "response",
               names_prefix = "support_") %>% 
  mutate(is_key = ifelse(grepl("key", support), "yes", "no"),
         support = str_remove(support, "^key_"),
         is_key = factor(is_key, levels = c("yes", "no"), labels = c("Ranked in top 3", "Selected"))) %>% 
  group_by(support, is_key) %>% 
  summarize(n = sum(response, na.rm = TRUE), .groups = "drop",
            pct = n/denom) %>% 
  mutate(support = case_when(
    support == "coaching" ~ "One on one coaching",
    support == "community" ~ "A community of practice",
    support == "dissemination" ~ "Help sharing outcome data with external audiences",
    support == "funds" ~ "Funding to purchase assessment tools",
    support == "info" ~ "Information about assessments",
    support == "leaders" ~ "Help for leaders to analyze and utilize data",
    support == "other" ~ "Some other type of support",
    support == "policy" ~ "Reducing the time required to assess 'traditional' outcomes",
    support == "teachers" ~ "Help for teachers to analyze and utilize data",
    support == "technical" ~ "Technical support",
    support == "workshop" ~ "Workshops on innovative assessments",
    TRUE ~ NA
  )) %>% 
  ggplot(., aes(pct, reorder(support, pct), fill = is_key)) +
  geom_col() +
  scale_fill_manual(values = c(
      "Ranked in top 3" = crpe_blues[2], 
      "Selected" = crpe_blues[1])) +
  scale_x_continuous(label = scales::label_percent(), 
                     expand = c(0, 0), 
                     limits = c(0, 1)) +
  scale_y_discrete(labels = wrap_format(35)) +
  labs(title = str_wrap("Type of Support Canopy School Leaders Need to Measure \"Nontraditional\" Outcomes", 34),
       subtitle = str_wrap("Sample limited to Canopy schools participating in 2024 Canopy survey (N = 189).", 67),
       x = "Percentage of Canopy schools",
       y = "",
       fill = NULL) +
  theme(legend.position = "bottom",
        legend.text = element_text(size = 10),
        panel.grid.major.y = element_blank(),
        axis.text.y = element_text(size = 12)) +
  geom_text(aes(label = scales::label_percent(accuracy = 1)(pct)), 
            position = position_stack(vjust = .5), 
            color = "white", 
            size = 5, 
            family = "sans") +
  guides(fill = guide_legend(title.hjust = 0.5,
                             nrow = 1,
                             reverse = T))
save_plots(fig_16, "figure_16")
ggsave(filename = "output/report-figures/eps/figure_16.eps",
       plot = fig_16,
       device = "eps",
       width = 9,
       height = 7)
```

```{r}
# Clean up
rm(fig_16, denom)
```

# Figure 17

```{r}
# Pulled from Gregor's code and modified - schools-practices-over-time
# Run model
wide <- import(here("data", "longitudinal/tags-wide.csv"))
volatility_data = 
  wide |>
  filter(n() > 1, .by = school_id) |>
  arrange(school_id, year) |>
  mutate(
    i_seq = row_number(),
    transition = case_when(
      i_seq == 1 ~ NA_character_,
      lag(year) >= 2022 ~ 'post_covid',
      year == 2021 ~ 'to_covid',
      lag(year) == 2021 ~ 'from_covid',
      year > 2021 & lag(year) == 2019 ~ 'skip_covid',
      .default = "PROBLEM"
    ),
    across(
      .cols = starts_with("practices"),
      \(x) c(0, abs(diff(x))) 
      # ^^^
      # take absolute difference from prev row
      # stick 0 on the front for first row
      # NAs (when tags weren't in use) will stay as NAs
    ),
    n_changes = rowSums(across(.cols = starts_with("practices")), na.rm = TRUE),
    .by = school_id
  ) |>
  filter(i_seq > 1) |> 
  select(!starts_with("practices"))

add_only_volatility = 
  wide |>
  filter(n() > 1, .by = school_id) |>
  arrange(school_id, year) |>
  mutate(
    i_seq = row_number(),
    transition = case_when(
      i_seq == 1 ~ NA_character_,
      lag(year) >= 2022 ~ 'post_covid',
      year == 2021 ~ 'to_covid',
      lag(year) == 2021 ~ 'from_covid',
      year > 2021 & lag(year) == 2019 ~ 'skip_covid',
      .default = "PROBLEM"
    ),
    across(
      .cols = starts_with("practices"),
      \(x) c(0, pmax(diff(x), 0)) 
      # ^^^
      # pmax instead of abs value to count only adds
      # NAs (when tags weren't in use) will stay as NAs
    ),
    n_changes = rowSums(across(.cols = starts_with("practices")), na.rm = TRUE),
    .by = school_id
  ) |>
  filter(i_seq > 1) |> 
  select(!starts_with("practices"))
## get demographics
xx = read_csv(here("data/longitudinal/combined-dat-ip.csv"))
xx = xx |>
  mutate(
    stu_poc_pct = 1 - self_reported_race_white,
  ) |>
  select(
    school_id,
    year = panel_year, 
    total_enroll = self_reported_total_enrollment,
    stu_poc_pct,
    locale, 
    school_descriptor,
    starts_with("grades")
  ) |>
  mutate(
    enroll_scaled = (total_enroll - mean(total_enroll, na.rm = TRUE)) / 
      sd(total_enroll, na.rm = TRUE),
    stu_poc_pct_scaled = (stu_poc_pct - mean(stu_poc_pct, na.rm = TRUE)) /
      sd(stu_poc_pct, na.rm = TRUE),
    locale = relevel(factor(locale), ref = "Urban"),
    school_descriptor = factor(
      school_descriptor,
      levels = c(1, 2, 3),
      labels = c("District", "Charter", "Private")
    ) 
  )

mm_vol = left_join(volatility_data, xx, by = c("school_id", "year"))
mm_add = left_join(add_only_volatility, xx, by = c("school_id", "year"))

mm_vol = mm_vol |>
  mutate(transition = relevel(factor(transition), ref = "post_covid"))
mm_add = mm_add |>
  mutate(transition = relevel(factor(transition), ref = "post_covid"))


missing_count =  mm_vol |> 
  is.na() |> 
  colSums() |> 
  sort(decreasing = TRUE) |> 
  data.frame(n_missing = _)
vol_mod = lm(
  n_changes ~ transition + stu_poc_pct_scaled + enroll_scaled + locale + school_descriptor +
     grades_elementary + grades_middle + grades_high,
  data = mm_vol
)
```

```{r}
# Extract coeffs
vol_coef = broom::tidy(vol_mod) |>
  arrange(desc(estimate)) |>
  mutate(term = fct_inorder(term),
         term = case_when(
           term == "transitionskip_covid" ~ "Excluding Covid (2021)",
           term == "transitionto_covid" ~ "Transition to Covid (2019-2021)",
           term == "(Intercept)" ~ "Baseline",
           term == "transitionfrom_covid" ~ "Transition from Covid (2021-2024)",
           term == "localeRural" ~ "Rural",
           term == "grades_elementary" ~ "Elementary schools",
           term == "localeMultiple" ~ "Multiple geographic locales",
           term == "enroll_scaled" ~ "Enrollment size",
           term == "school_descriptorPrivate" ~ "Private (independent) school",
           term == "school_descriptorCharter" ~ "Public charter school",
           term == "stu_poc_pct_scaled" ~ "% BIPOC students",
           term == "localeSuburban" ~ "Suburban",
           term == "grades_high" ~ "High schools",
           term == "grades_middle" ~ "Middle schools"
         )) 
```

```{r}
# Pull baseline to center in plot
intercept <- vol_coef %>% filter(term == "Baseline") %>% pull(estimate)
# Adjust coefficients around baseline
plot_dat <- vol_coef %>% 
  mutate(
    deviation = estimate - intercept,
    sig = ifelse(p.value < .05, "yes", "no")
  ) %>% 
  filter(term != "Baseline")
# Build plot
fig_17 <- ggplot(plot_dat, aes(y = reorder(term, -estimate), x = deviation, fill = sig)) +
  geom_bar(stat = "identity") +
  scale_fill_manual(values = c(
    "no" = crpe_grays[1],
    "yes" = crpe_blues[1]
  )) +
  scale_x_continuous(limits = c(-8, 10), expand = expansion()) +
  labs(
    x = "Estimated number of practices added or dropped",
    y = "",
    title = str_wrap("Estimated Effect on Number of Practices Modified by Schools Between Survey Responses", 35),
    subtitle = str_wrap("Bars in blue indicate a statistically significant relationship. The baseline is set at 0.", 65)
  ) +
  theme(
    panel.grid.major.y = element_blank(),
    legend.position= "none"
  ) 
save_plots(fig_17, "figure_17")
ggsave(filename = "output/report-figures/eps/figure_17.eps",
       plot = fig_17,
       device = "eps",
       width = 9,
       height = 7)
```

```{r}
# Clean up
rm(add_only_volatility, fig_17, missing_count, mm_add, mm_vol, plot_dat, vol_coef, vol_mod, volatility_data, wide, xx, intercept)
```

# Figure 18

```{r}
# Prep
# ID 3+ year schools
id <- long_tags %>% 
  select(school_id, year) %>% 
  group_by(school_id) %>% 
  summarize(n_year = n_distinct(year)) %>% 
  ungroup() %>% 
  filter(n_year > 2) %>% 
  pull(school_id)
# Pull Ns
# Pull Ns for each year
n_2019 <- long_tags %>% filter(year == 2019 & school_id %in% id) %>% summarize(n = n_distinct(school_id)) %>% pull()
n_2021 <- long_tags %>% filter(year == 2021 & school_id %in% id) %>% summarize(n = n_distinct(school_id)) %>% pull()
n_2022 <- long_tags %>% filter(year == 2022 & school_id %in% id) %>% summarize(n = n_distinct(school_id)) %>% pull()
n_2023 <- long_tags %>% filter(year == 2023 & school_id %in% id) %>% summarize(n = n_distinct(school_id)) %>% pull()
n_2024 <- long_tags %>% filter(year == 2024 & school_id %in% id) %>% summarize(n = n_distinct(school_id)) %>% pull()
```

```{r}
# Pull relevant tags
subset <- c("practices_student_projects", "practices_competency_education", "practices_performance_assessment", "practices_design_thinking", "practices_place_based")
# Build plot
fig_18 <- long_tags %>% 
  filter(var %in% subset) %>% 
  filter(school_id %in% id) %>% 
  group_by(var, year) %>% 
  summarize(n = sum(usage)) %>% 
  mutate(pct = case_when(
    year == 2019 ~ n/n_2019,
    year == 2021 ~ n/n_2021,
    year == 2022 ~ n/n_2022,
    year == 2023 ~ n/n_2023,
    year == 2024 ~ n/n_2024
  )) %>% 
  left_join(labels, by = "var") %>% 
  mutate(label = ifelse(label == "Performance based assessment", "Performance-based assessment", label)) %>% 
  ggplot(., aes(year, pct, color = label)) +
  geom_line() +
  geom_point() +
  scale_color_manual(values = c(crpe_blues[1], crpe_blues[3], crpe_oranges[1], crpe_purples[1], crpe_purples[3])) +
  scale_x_continuous(limits = c(2019, 2024),
                     expand = c(0.01, 0),
                     breaks = unique(long_dat$year)) +
  scale_y_continuous(expand = c(0, 0),
                     limits = c(0, 1),
                     labels = scales::percent_format(accuracy = 1)) +
  theme(panel.grid.major.x = element_blank(),
        legend.position = "bottom",
        legend.text = element_text(size = 10),
        legend.title = element_text(size = 10)) +
  labs(x = "",
       y = "Percentage of Canopy schools",
       title = str_wrap("Changes in Select Practices Related to Relevant and Engaging Instruction 2019\u20132024", 48),
       subtitle = str_wrap("Sample limited to schools that participated 3 or more times in a Canopy survey (N = 119).", 80),
       color = "Select practices") +
  guides(color = guide_legend(title.position = "top",
                              title.hjust = 0.5,
                              nrow = 2))
save_plots(fig_18, "figure_18")
ggsave(filename = "output/report-figures/eps/figure_18.eps",
       plot = fig_18,
       device = "eps",
       width = 9,
       height = 7)
```

```{r}
# Clean up
rm(subset, fig_18)
```

# Figure 19

## Waffling

```{r include = FALSE}
#read in data
long = import(here("data/longitudinal", "tags-long.csv"))
#get vector of 4-year tags
tags_4y = long |>
  filter(usage == 1) |>
  filter(n_distinct(year) >= 4, .by = var) |>
  pull(var) |>
  unique()
long_4y = long |> filter(var %in% tags_4y)
#get schools
sch = import(here("data/long_school.csv")) |>
  summarize(n_years = n_distinct(year), .by = c(school_id, school_name))
## append 2024 schools - G's temp fix
sch = long |>
  summarize(
    n_years = n_distinct(year),
    .by = school_id
  ) |>
  left_join(
    select(sch, school_id, school_name)
  )
# J's original analysis - includes pieces that can't be removed
potential_wafflers = long_4y |>
  distinct(school_id, year) |>
  filter(n_distinct(year) >= 3, .by = school_id) |>
  summarize(
    years = toString(year),
    could_covid_waffle = 2019 %in% year & 2021 %in% year,
    could_waffle_2022 = 2021 %in% year & 2022 %in% year,
    could_waffle_2023 = 2022 %in% year & 2023 %in% year,
    could_waffle_2024 = 2023 %in% year & 2024 %in% year,
    .by = school_id
  )

waffle_denom = potential_wafflers |>
  summarize(across(starts_with("could"), sum))

waffle_all = long_4y |>
  filter(
    1 %in% usage,    ## present at least once
    n() > 2,         ## at least 3 survey responses
    .by = c(var, school_id)
  ) |> 
  mutate(
    added = any(diff(usage) == 1),
    dropped = any(diff(usage) == -1),
    all_1 = all(usage == 1),
    waffled = added & dropped,
    waffle_bump = waffled & last(usage, na_rm = TRUE) == 0,
    waffle_dip = waffled & last(usage, na_rm = TRUE) == 1,
    .by = c(var, school_id)
  ) |>
  pivot_wider(names_from = year, values_from = usage) |>
  left_join(sch, by = "school_id") |>
  select(school_id, school_name, tag = var, `2019`:`2024`, added, dropped, all_1, starts_with("waffle")) |>
  arrange(school_id, desc(waffled)) |>
  mutate(
    binary_summary = paste(`2019`, `2021`, `2022`, `2023`, `2024`, sep = ","),
    waffle_type = case_when(
      `2019` == 0 & `2021` == 1 & waffled ~ "COVID bump",
      `2019` == 1 & `2021` == 0 & waffled ~ "COVID dip",
      `2021` == 0 & `2022` == 1 & waffled ~ "2022 bump",
      `2021` == 1 & `2022` == 0 & waffled ~ "2022 dip",
      `2022` == 0 & `2023` == 1 & waffled ~ "2023 bump",
      `2022` == 1 & `2023` == 0 & waffled ~ "2023 dip",
      `2023` == 0 & `2024` == 1 & waffled ~ "2024 bump",
      `2023` == 1 & `2024` == 0 & waffled ~ "2024 dip"
    )
  ) 

plot_dat <- waffle_all |>
  filter(waffled) |>
  count(waffle_type) |>
  filter(!is.na(waffle_type)) |>
  separate_wider_delim(waffle_type, delim = " ", names = c("pandemic", "type")) |>
  pivot_wider(names_from = type, values_from = n) |>
  arrange(pandemic) |> ### COVID on top
  mutate(
    all_waffles = bump + dip,
    n_schools_that_could_waffle = c(waffle_denom$could_waffle_2022, waffle_denom$could_waffle_2023, waffle_denom$could_waffle_2024, waffle_denom$could_covid_waffle),
    waffles_per_school = all_waffles / n_schools_that_could_waffle
  )

# Gregor's fix
wafflers = long_4y |>
  ## keep only school/tag combos with at least 3 years
  filter(n_distinct(year) >= 3, .by = c(school_id, var)) |>
  arrange(school_id, var, year) |> 
  mutate(
    diff = c(NA, diff(usage)),
    .by = c(school_id, var)
  ) |>
  summarize(
    usage_string = paste(usage, collapse = ""),
    diff_string = paste(diff[-1], collapse = ""),
    year_string = paste(year, collapse = ", "),
    is_waffle = -1 %in% diff & 1 %in% diff,
    is_dip = is_waffle & which.min(diff) < which.max(diff),
    is_bump = is_waffle & which.max(diff) < which.min(diff),
    dip_years = if(is_dip) list(year[usage == 0]) else list(NULL),
    bump_years = if(is_bump) list(year[usage == 1]) else list(NULL),
    waffle_years = coalesce(dip_years, bump_years),
    potential_years = list(tail(head(year, -1), -1)),
    is_multi_waffle = sum(diff == 1, na.rm = TRUE) > 1 | sum(diff == -1, na.rm = TRUE) > 1,
    .by = c(school_id, var)
  )

waffle_summary = wafflers |>
  filter(!is_multi_waffle) |>
  unnest(potential_years) |>
  mutate(waffle_this_year = potential_years %in% waffle_years, 
         .by = c(school_id, var, potential_years)) |>
  summarize(
    waffle_possible = n(),
    waffle_count = sum(waffle_this_year),
    bump_count = sum(waffle_this_year & is_bump),
    dip_count = sum(waffle_this_year & is_dip),
    waffle_pct = mean(waffle_this_year),
    n_sch = n_distinct(school_id),
    waffle_per_sch = waffle_count / n_sch,
    .by = potential_years
  )
#plot
fig_19 <- ggplot(waffle_summary, aes(factor(potential_years), waffle_per_sch)) +
  geom_segment(aes(
                   xend = factor(potential_years),
                   y = 0, 
                   yend = waffle_per_sch), 
                   color = crpe_blues[1]) +
  geom_point(size = 5, color = crpe_oranges[1]) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, 4)) +
  labs(x = "", 
       y = "Average switchbacks per school", 
       title = "Average switchbacks per school from 2021-2023") +
  theme(panel.grid.major.x = element_blank(),
        panel.grid.minor.x = element_blank())

# Save
save_plots(fig_19, "figure_19")
ggsave(filename = "output/report-figures/eps/figure_19.eps",
       plot = fig_19,
       device = "eps",
       width = 9,
       height = 7)

# clean up
rm(long_4y, plot_dat, potential_wafflers, sch, waffle_all, waffle_denom, waffle_summary, wafflers, long, tags_4y)
```